default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local: &local
  host: localhost
  username: lockdown_coundown
  password: dedev

development:
  <<: *default
  <<: *local
  database: lockdown_coundown_development

test:
  <<: *default
  <<: *local
  database: lockdown_coundown_test

